// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syymqotfxkmchtjsmhkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5eW1xb3RmeGttY2h0anNtaGtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3ODAwMTAsImV4cCI6MjA3MjM1NjAxMH0.5lAdZFVVTL6sulWF1gIPS8dWe0CUFc4a6PHl1V23u6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});